default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: tsubuyaitter_development

test:
  <<: *default
  database: tsubuyaitter_test

production:
  <<: *default
  database: tsubuyaitter_production
  username: tsubuyaitter
  password: <%= ENV['TSUBUYAITTER_DATABASE_PASSWORD'] %>
